server:
  port: 7070

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: root
  redis:
    host: localhost
    database: 2
    port: 6379
  data:
    redis:
      repositories:
        enabled: true
#开启日志输出样式
logging:
  level:
    com:
      bigevent:
        mapper: debug
        service: info
        controller: info
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bigevent.pojo
  #  驼峰命名
  configuration:
    map-underscore-to-camel-case: true

#jwt配置
bigevent:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: long
    # 设置jwt过期时间
    admin-ttl: 86400000
    # 设置前端传递过来的令牌名称
    admin-token-name: Authorization
  #阿里OSS配置
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tEnArYswmDPcSLZ95Tt
    access-key-secret: ExLIQJYJ7oQThLQuoG2p1lzHMW7WsI
    bucketName: big-event-long01


#pagehelper分页插件配置
page helper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql



